version: 2

sources:
  - name: managed_layer
    database: dbt           #database name
    schema: raw       # Your actual schema name
    tables:
      - name: trade_load
        description: "Raw trades data ingested via Snowpipe from S3"
        
      - name: market_price_load
        description: "Raw price data ingested via Snowpipe from S3"